project:
  type: book

book:
  title: "WeData's Ultimate R Book"
  author: ["Vestin Hategekimana"]
  date: "2024-01-21"
  chapters:
    - index.qmd
    - part: "Base R"
      chapters:
        - intro.qmd
        - summary.qmd
        - references.qmd
    - part: "Math with R"
    - part: "Tidyverse"
    - part: "Statistical analysis"
    - part: "Machine learning"
    - part: "Text mining/NLP"
    - part: "Web scraping"

bibliography: references.bib

execute: 
  freeze: auto

format:
  html:
    theme: cosmo
    include-in-header: "scripts/translate.html"
  pdf:
    documentclass: scrreprt

engine: knitr

editor: visual

