on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown
            any::downlit
            any::xml2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install dependencies with renv
        uses: r-lib/actions/setup-renv@v2
        env:
          RENV_CONFIG_REPOS_OVERRIDE: https://cloud.r-project.org
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
          R_COMPILE_AND_INSTALL_PACKAGES: never
