name: Render and Publish
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.3.340

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'

      - name: Set CRAN Mirror
        run: R -e 'options(repos = c(CRAN = "https://cloud.r-project.org"))'
          
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev libxml2-dev libssl-dev

      - name: Install dependencies with renv
        uses: r-lib/actions/setup-renv@v2
        env:
          RENV_CONFIG_REPOS_OVERRIDE: https://cloud.r-project.org
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
          R_COMPILE_AND_INSTALL_PACKAGES: never

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}